#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Léger Massimo
# Janvier 2020


import pygame, sys, math


pygame.init()
w,h = 800,700; cx,cy = w//2, h//2
screen = pygame.display.set_mode((w,h))
clock =  pygame.time.Clock()

lcam = 220 # "focale" de la caméra

vertexes = (-100, -100, 0),(-100,100,0),(100,-100,0),(100,100,0),(-100, -100, 200),(-100,100,200),(100,-100,200),(100,100,200) #cube

iterator = 0
while True:
    dt = clock.tick()/1000
    iterator += 1

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    screen.fill((50,50,50)) #remplissage de fond, RGB

    for x,y,z in vertexes:
        z/=2
        z-=400# distance d'observation de la scène
        x += 230
        y -= 170
        
        x -= iterator
        #lcam += iterator/300
        
        
        #f = 200/z
        #x,y = x*f,y*f
        
        
        x_apparent = lcam*x/z
        y_apparent = lcam*y/z

        pygame.draw.circle(screen, (250,250,250), (cx + int(x_apparent), cy + int(y_apparent)), 3) #(surface, color, center, radius, {width} )  - {} signifiant paramètre facultatif

    pygame.display.flip()
